#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f RV32I.vcd

#run Verilator to transform Verilog into C++, including C++ testbench
#(this operation is what is called creating a wrapper)
verilator -Wall --cc --trace RV32I.sv --exe RV32I_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRV32I.mk VRV32I

#run executable simulation file
obj_dir/VRV32I